function ThreadTest(numTimes, numThreads)
        animation_setup(1);
        import SVGRendering.SVGRenderer.*;

    % Finds full path to this file, animation_setup.    
    thisFileName = mfilename('fullpath');
    
    % Extracts the folder path from the file. Note that we do not care
    % about the name of this file.
    [ThisFolder, ~] = fileparts(thisFileName);        
        
        renderer = SVGRenderer();
        renderer.SetWorkerNo(1);
        
        renderer2 = SVGRenderer();
        renderer2.SetWorkerNo(2);
             
        indiv = divvy(...
            {...
            fullfile(ThisFolder,'threadtestframes','this.svg'),...
            fullfile(ThisFolder,'threadtestframes','this2.svg'),...
            fullfile(ThisFolder,'threadtestframes','this3.svg'),...
            fullfile(ThisFolder,'threadtestframes','this4.svg'),...
            fullfile(ThisFolder,'threadtestframes','this5.svg'),...
            fullfile(ThisFolder,'threadtestframes','this6.svg')...
            },2);
        outdiv = divvy(...
            {...
            fullfile(ThisFolder,'threadtestframes','this.png'),...
            fullfile(ThisFolder,'threadtestframes','this2.png'),...
            fullfile(ThisFolder,'threadtestframes','this3.png'),...
            fullfile(ThisFolder,'threadtestframes','this4.png'),...
            fullfile(ThisFolder,'threadtestframes','this5.png'),...
            fullfile(ThisFolder,'threadtestframes','this6.png')...
            },2);
        
        renderer.SetInputFilenames(indiv{1});
        renderer.SetOutputFilenames(outdiv{1});
        renderer.SetOutputFormat('PNG');
        
       renderer2.SetInputFilenames(indiv{2});
       renderer2.SetOutputFilenames(outdiv{2});
        renderer2.SetOutputFormat('PNG');
        
       %renderer.RenderImage(fullfile(ThisFolder,'threadtestframes''this.svg'),fullfile(ThisFolder,'threadtestframes''this.svg'));
        %renderer.RenderImageBatch();
        
        renderer.start();
        renderer2.start();
        
%         renderer.SetNumWorkers(numThreads);
%         renderer.RenderImages({...
%             fullfile(ThisFolder,'threadtestframes''this.svg'),...
%             fullfile(ThisFolder,'threadtestframes''this2.svg'),...
%             fullfile(ThisFolder,'threadtestframes''this3.svg'),...
%             fullfile(ThisFolder,'threadtestframes''this4.svg'),...
%             fullfile(ThisFolder,'threadtestframes''this5.svg'),...
%             fullfile(ThisFolder,'threadtestframes''this6.svg')...
%             },{...
%             fullfile(ThisFolder,'threadtestframes''this.jpg'),...
%             fullfile(ThisFolder,'threadtestframes''this2.jpg'),...
%             fullfile(ThisFolder,'threadtestframes''this3.jpg'),...
%             fullfile(ThisFolder,'threadtestframes''this4.jpg'),...
%             fullfile(ThisFolder,'threadtestframes''this5.jpg'),...
%             fullfile(ThisFolder,'threadtestframes''this6.jpg')...
%             });
end

